//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1055 with alias "tabContent"
	/// <summary>Tab - Content</summary>
	public partial interface ITabContent : IPublishedContent
	{
		/// <summary>Body</summary>
		Our.Umbraco.Vorto.Models.VortoValue<IHtmlString> Body { get; }

		/// <summary>Title</summary>
		Our.Umbraco.Vorto.Models.VortoValue<string> Title { get; }
	}

	/// <summary>Tab - Content</summary>
	[PublishedContentModel("tabContent")]
	public partial class TabContent : PublishedContentModel, ITabContent
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "tabContent";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public TabContent(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<TabContent, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Body
		///</summary>
		[ImplementPropertyType("body")]
		public Our.Umbraco.Vorto.Models.VortoValue<IHtmlString> Body
		{
			get { return GetBody(this); }
		}

		/// <summary>Static getter for Body</summary>
		public static Our.Umbraco.Vorto.Models.VortoValue<IHtmlString> GetBody(ITabContent that) { return that.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<IHtmlString>>("body"); }

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> Title
		{
			get { return GetTitle(this); }
		}

		/// <summary>Static getter for Title</summary>
		public static Our.Umbraco.Vorto.Models.VortoValue<string> GetTitle(ITabContent that) { return that.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<string>>("title"); }
	}
}
