//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1057 with alias "tabNavigation"
	/// <summary>Tab - Navigation</summary>
	public partial interface ITabNavigation : IPublishedContent
	{
		/// <summary>Hide In XML Sitemap</summary>
		bool HideInXmlsitemap { get; }

		/// <summary>Internal Redirect</summary>
		IPublishedContent UmbracoInternalRedirectId { get; }

		/// <summary>Redirect To</summary>
		IPublishedContent UmbracoRedirect { get; }
	}

	/// <summary>Tab - Navigation</summary>
	[PublishedContentModel("tabNavigation")]
	public partial class TabNavigation : PublishedContentModel, ITabNavigation
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "tabNavigation";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public TabNavigation(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<TabNavigation, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Hide In XML Sitemap
		///</summary>
		[ImplementPropertyType("hideInXMLSitemap")]
		public bool HideInXmlsitemap
		{
			get { return GetHideInXmlsitemap(this); }
		}

		/// <summary>Static getter for Hide In XML Sitemap</summary>
		public static bool GetHideInXmlsitemap(ITabNavigation that) { return that.GetPropertyValue<bool>("hideInXMLSitemap"); }

		///<summary>
		/// Internal Redirect
		///</summary>
		[ImplementPropertyType("umbracoInternalRedirectId")]
		public IPublishedContent UmbracoInternalRedirectId
		{
			get { return GetUmbracoInternalRedirectId(this); }
		}

		/// <summary>Static getter for Internal Redirect</summary>
		public static IPublishedContent GetUmbracoInternalRedirectId(ITabNavigation that) { return that.GetPropertyValue<IPublishedContent>("umbracoInternalRedirectId"); }

		///<summary>
		/// Redirect To
		///</summary>
		[ImplementPropertyType("umbracoRedirect")]
		public IPublishedContent UmbracoRedirect
		{
			get { return GetUmbracoRedirect(this); }
		}

		/// <summary>Static getter for Redirect To</summary>
		public static IPublishedContent GetUmbracoRedirect(ITabNavigation that) { return that.GetPropertyValue<IPublishedContent>("umbracoRedirect"); }
	}
}
