//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1058 with alias "tabSEO"
	/// <summary>Tab - SEO</summary>
	public partial interface ITabSeo : IPublishedContent
	{
		/// <summary>Meta Description</summary>
		Our.Umbraco.Vorto.Models.VortoValue<string> MetaDescription { get; }

		/// <summary>Meta Keywords</summary>
		Our.Umbraco.Vorto.Models.VortoValue<string> MetaKeywords { get; }

		/// <summary>Meta Title</summary>
		Our.Umbraco.Vorto.Models.VortoValue<string> MetaTitle { get; }
	}

	/// <summary>Tab - SEO</summary>
	[PublishedContentModel("tabSEO")]
	public partial class TabSeo : PublishedContentModel, ITabSeo
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "tabSEO";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public TabSeo(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<TabSeo, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Meta Description
		///</summary>
		[ImplementPropertyType("metaDescription")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> MetaDescription
		{
			get { return GetMetaDescription(this); }
		}

		/// <summary>Static getter for Meta Description</summary>
		public static Our.Umbraco.Vorto.Models.VortoValue<string> GetMetaDescription(ITabSeo that) { return that.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<string>>("metaDescription"); }

		///<summary>
		/// Meta Keywords
		///</summary>
		[ImplementPropertyType("metaKeywords")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> MetaKeywords
		{
			get { return GetMetaKeywords(this); }
		}

		/// <summary>Static getter for Meta Keywords</summary>
		public static Our.Umbraco.Vorto.Models.VortoValue<string> GetMetaKeywords(ITabSeo that) { return that.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<string>>("metaKeywords"); }

		///<summary>
		/// Meta Title
		///</summary>
		[ImplementPropertyType("metaTitle")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> MetaTitle
		{
			get { return GetMetaTitle(this); }
		}

		/// <summary>Static getter for Meta Title</summary>
		public static Our.Umbraco.Vorto.Models.VortoValue<string> GetMetaTitle(ITabSeo that) { return that.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<string>>("metaTitle"); }
	}
}
